/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/service/configure-device": {
    post: operations["configure_device"];
  };
  "/service/connect-device": {
    post: operations["connect_device"];
  };
  "/service/interrupt-device-init": {
    post: operations["interrupt_device_init"];
  };
  "/service/obtain-device-conf-info": {
    post: operations["obtain_device_conf_info"];
  };
  "/service/start-device-init": {
    post: operations["start_device_init"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ConfigureDeviceRequest: {
      confs: (components["schemas"]["DeviceConfEntry"])[];
      /** Format: int32 */
      device_id: number;
    };
    ConnParam: {
      name: string;
      value: components["schemas"]["ConnParamValType"];
    };
    ConnParamConf: {
      name: string;
      typ: components["schemas"]["ConnParamType"];
    };
    /** @enum {string} */
    ConnParamType: "Bool" | "Int" | "Float" | "String";
    ConnParamValType: OneOf<[{
      Bool: boolean;
    }, {
      /** Format: int32 */
      Int: number;
    }, {
      /** Format: float */
      Float: number;
    }, {
      String: string;
    }]>;
    ConnectDeviceRequest: {
      connect_conf: (components["schemas"]["ConnParam"])[];
      /** Format: int32 */
      device_id: number;
    };
    DeviceConfEntry: {
      data?: components["schemas"]["DeviceConfType"];
      /** Format: int32 */
      id: number;
    };
    DeviceConfInfoEntry: {
      data: components["schemas"]["DeviceConfInfoEntryType"];
      /** Format: int32 */
      id: number;
      name: string;
    };
    DeviceConfInfoEntryChoiceList: {
      choices: (string)[];
      /** Format: int32 */
      default?: number;
      required: boolean;
    };
    DeviceConfInfoEntryFloat: {
      /** Format: float */
      default?: number;
      /** Format: float */
      gt?: number;
      /** Format: float */
      lt?: number;
      /** Format: float */
      neq?: number;
      required: boolean;
    };
    DeviceConfInfoEntryFloatRange: {
      /** Format: float */
      def_from?: number;
      /** Format: float */
      def_to?: number;
      /** Format: float */
      max: number;
      /** Format: float */
      min: number;
      required: boolean;
    };
    DeviceConfInfoEntryInt: {
      /** Format: int32 */
      default?: number;
      /** Format: int32 */
      gt?: number;
      /** Format: int32 */
      lt?: number;
      /** Format: int32 */
      neq?: number;
      required: boolean;
    };
    DeviceConfInfoEntryIntRange: {
      /** Format: int32 */
      def_from?: number;
      /** Format: int32 */
      def_to?: number;
      /** Format: int32 */
      max: number;
      /** Format: int32 */
      min: number;
      required: boolean;
    };
    DeviceConfInfoEntryJSON: {
      default?: string;
      required: boolean;
    };
    DeviceConfInfoEntryString: {
      default?: string;
      match_regex?: string;
      /** Format: int32 */
      max_len?: number;
      /** Format: int32 */
      min_len?: number;
      required: boolean;
    };
    DeviceConfInfoEntryType: OneOf<[{
      String: components["schemas"]["DeviceConfInfoEntryString"];
    }, {
      Int: components["schemas"]["DeviceConfInfoEntryInt"];
    }, {
      IntRange: components["schemas"]["DeviceConfInfoEntryIntRange"];
    }, {
      Float: components["schemas"]["DeviceConfInfoEntryFloat"];
    }, {
      FloatRange: components["schemas"]["DeviceConfInfoEntryFloatRange"];
    }, {
      JSON: components["schemas"]["DeviceConfInfoEntryJSON"];
    }, {
      ChoiceList: components["schemas"]["DeviceConfInfoEntryChoiceList"];
    }, {
      Section: (components["schemas"]["DeviceConfInfoEntry"])[];
    }]>;
    DeviceConfType: OneOf<[{
      String: string;
    }, {
      /** Format: int32 */
      Int: number;
    }, {
      IntRange: (number)[];
    }, {
      /** Format: float */
      Float: number;
    }, {
      FloatRange: (number)[];
    }, {
      JSON: string;
    }, {
      /** Format: int32 */
      ChoiceList: number;
    }]>;
    DeviceStartInitRequest: {
      /** Format: byte */
      device_name: string;
      /** Format: binary */
      module_file: string;
    };
    DeviceStartInitResponse: {
      conn_params: (components["schemas"]["ConnParamConf"])[];
      /** Format: int32 */
      device_id: number;
    };
    InterruptDeviceInitRequest: {
      /** Format: int32 */
      device_id: number;
    };
    ObtainDeviceConfInfoRequest: {
      /** Format: int32 */
      device_id: number;
    };
    ObtainDeviceConfInfoResponse: {
      device_conf_info: (components["schemas"]["DeviceConfInfoEntry"])[];
    };
    TestUploadForm: {
      /** Format: binary */
      file: string;
      /** Format: byte */
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  configure_device: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigureDeviceRequest"];
      };
    };
    responses: {
      /** @description Ok response */
      200: never;
      /** @description Server error response */
      500: never;
    };
  };
  connect_device: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectDeviceRequest"];
      };
    };
    responses: {
      /** @description Ok response */
      200: never;
      /** @description Server error response */
      500: never;
    };
  };
  interrupt_device_init: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterruptDeviceInitRequest"];
      };
    };
    responses: {
      /** @description Ok response */
      200: never;
      /** @description Server error response */
      500: never;
    };
  };
  obtain_device_conf_info: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ObtainDeviceConfInfoRequest"];
      };
    };
    responses: {
      /** @description Ok response with device conf info */
      200: {
        content: {
          "application/json": components["schemas"]["ObtainDeviceConfInfoResponse"];
        };
      };
      /** @description Server error response */
      500: never;
    };
  };
  start_device_init: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["DeviceStartInitRequest"];
      };
    };
    responses: {
      /** @description Ok response with device id and connection params */
      200: {
        content: {
          "application/json": components["schemas"]["DeviceStartInitResponse"];
        };
      };
      /** @description Server error response */
      500: never;
    };
  };
}
